### ISSUE TITLE
Enable for all tests by default?

### ISSUE THREAD

**Issue by alfuken** [tjwp/aggregate_assertions#1]
Hi,

Is it possible to have this enabled for all tests by default, without having to enclose thousands of test cases?

If it's not currently, are there plans to add such functionality? Would be a great addition, IMO. :)

Thanks!

**Comment by tjwp** [comment]
That is an interesting suggestion that I had not thought of!

I'd have to look more to understand the feasibility, and this would probably need to be optional behavior, but I'm certainly open to it.

When I have time I'll investigate, but I'm also open to PRs that would add this.

**Comment by tjwp** [comment]
@alfuken I've opened a PR with support for enabling for all tests: #2 

If you want to try it out you can point to the branch [tjwp-everywhere](https://github.com/tjwp/aggregate_assertions/tree/tjwp-everywhere).

It seems to be working well but I want to add a few more tests of setup and teardown errors before I merge it.

**Comment by alfuken** [comment]
Seems to be working. Thanks! :)

**Comment by tjwp** [comment]
Released as v0.2.0. Thanks for the suggestion!
